### ISSUE TITLE
[QUESTION] Permissions

### ISSUE THREAD

**Issue by cycycy-g** [RedstoneDaedalus/discord.js-base-class#3]
Hi! I really like the structure of the commands. I just have one question that's been bothering me.

How does a command check for permissions?
Example, I wanna make a command that only Admins can use:

```
 class Ping extends Base {
  constructor(client) {
    // Initialise base command and pass data - all properties except name are optional
    super(client, {
      name: "ping",
      description: "Pings the bot.",
      usage: "", // Usage does not include the command - it is simply the arguments passed
      category: "Information",
      cooldown: 1000,
      aliases: ["pong"],
      // permLevel is interchangable with permission, although you can have both
      permLevel: 0,
      permission: "ADMINISTRATOR" // Which code does the command check this? is it in Command Class? Do I have to make a function to check whether or not the user has this permission?
    });
  }
  
  run(message) {
    // Respond with the time between now and when the user sent their message
    super.respond(`Pong! Took ${message.createdAt - Date.now()}ms.`);
  }
}

// Export the class
module.exports = Ping;
```

**Comment by RedDaedalus** [comment]
Hi! The permission code is not currently in this repo, as it never got truly finished. In fact I should probably archive it since I question if it will even work today due to discord’s gateway changes. If you still want to use it, I can add code for permission checks.

**Comment by cycycy-g** [comment]
@RedstoneDaedalus Sorry for late reply, i figured it out on my own. Thanks for the reply tho even if this repo is not maintained.
