### ISSUE TITLE
[QUESTION] Partials

### ISSUE THREAD

**Issue by ghost** [RedstoneDaedalus/discord.js-base-class#4]
Hello, i really like your base class,
but where i can place the partials (in discord.js v12) ?

Thanks ! 😄

**Comment by RedDaedalus** [comment]
Hello,

This project is not maintained and has not been maintained for years. I just keep forgetting to archive the repository. I don't personally use DJS anymore, so you will have to ask somebody more familiar with v12. Your best bet is their support server. Let me know if you have any questions.
